apiVersion: v1
kind: ServiceAccount         #sa are similar to users but bit differ it use for non human access (api calls , pipeline sececution , promethesus , grafana)
metadata:
  name: dev-pipeline-sa
  namespace: dev